### ISSUE TITLE
Problem launching the emulator

### ISSUE THREAD

**Issue by edwardpham** [google/link022#77]
When I do step 3 - Start the Emulator, I got the following error:
sudo env -u TERM python emulator.py   --target_cmd "../binary/link022_agent -ca ../demo/cert/server/ca.crt \
  -cert ../demo/cert/server/server.crt \
  -key ../demo/cert/server/server.key -eth_intf_name target-eth1 \
  -wlan_intf_name target-eth2"
Traceback (most recent call last):
  File "emulator.py", line 127, in <module>
    emulator.start()
  File "emulator.py", line 83, in start
    self._start_topo()
  File "emulator.py", line 103, in _start_topo
    params1=params1, params2=params2)
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 287, in addLink
    return cls( node1, node2, **defaults )
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 342, in __init__
    port1 = node1.newPort()
AttributeError: 'str' object has no attribute 'newPort'

I have the latest mininet installed. This is on an Ubuntu machine.
Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by boleifu** [comment]
Are you using mininet 2.2.1?
Based on the mininet API doc, the addLink method accepts node names as inputs. http://mininet.org/api/classmininet_1_1net_1_1Mininet.html#ae01361739c8c8a4ab26a6bf12517d541
